version: "3.9"

services:
  app:
    image: node:15.6.0-stretch
    container_name: app
    depends_on: 
      - mongo
    working_dir: /home/app
    volumes: 
      - ./:/home/app
    tty: true
    stdin_open: true

  mongo:
    image: mongo:4.4.3-bionic
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev

  mongo-express:
    image: mongo-express:0.54.0
    depends_on: 
      - mongo
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev

secrets:
  mongo_uri:
    file: mongo_uri.secret
  scale_serp_key:
    file: scale_serp_key.secret